title: Pangolim
description: Pangolim é a base de conhecimento prática para Linux, infraestrutura, DevOps, Kubernetes, redes, monitoramento e troubleshooting.

exclude:
  - "*.bak"
  - "*.bkp"
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - README.md
  - docs/